from scipy import *
from scipy.linalg import *

m1 = array( [ [ 1/2, 1/3 ], [ -2/7, 2/ 8 ]] )
m2 = array( [ [ -1/3, 2/7 ], [ 2/5, -1/7 ]] )
m3 = array( [ [ -1/5,2/3], [1/8, 3/11] ] )
p = array( [ [ -1/30, 2/21 ], [ 41/210, -23/196 ] ] )
I = array( [ [ 42, -56 ], [ 48, 84 ]] ) / 37
v = array( [3.0, -1])

def solution():
    print("---------------------------------------------------------------")
    print("Here are the answers of Alinur Amangazy")
    print("---------------------------------------------------------------")

    print("This is part 1.")
    print()
    print("dot(m1,m2) is equal to: \n")
    print(dot(m1,m2))
    print()
    print("p is equal to: \n")
    print(p)
    print()
    print("dot(m1,m2) - p is equal to: \n")
    print(dot(m1,m2) - p)
    print()
    print("---------------------------------------------------------------")

    print("This is part 2.")
    print()
    print("inv(m1) is equal to: \n")
    print(inv(m1))
    print()
    print("I is equal to: \n")
    print(I)
    print()
    print("inv(m1) - I is equal to: \n")
    print(inv(m1) - I)
    print()
    print("---------------------------------------------------------------")

    print("This is part 3.")
    print()
    print("(m1.m2).m3 is equal to: \n")
    print(dot(dot(m1,m2), m3))
    print()
    print("m1.(m2.m3) is equal to: \n")
    print(dot(m1,dot(m2,m3)))
    print()
    print("(m1.m2).m3 - m1.(m2.m3) is equal to: \n")
    print(dot(dot(m1,m2), m3) - dot(m1,dot(m2,m3)))
    print()
    print("---------------------------------------------------------------")

    print("This is part 4.a.")
    print()
    print("m1.(m2+m3) is equal to: \n")
    print(dot(m1,(m2+m3)))
    print()
    print("m1.m2 + m1.m3 is equal to: \n")
    print(dot(m1,m2) + dot(m1,m3))
    print()
    print("m1.(m2+m3) - (m1.m2 + m1.m3) is equal to: \n")
    print(dot(m1,(m2+m3)) - (dot(m1,m2) + dot(m1,m3)))
    print()
    print("---------------------------------------------------------------")

    print("This is part 4.b.")
    print()
    print("(m1+m2).m3 is equal to: \n")
    print(dot((m1+m2),m3))
    print()
    print("m1.m3 + m2.m3 is equal to: \n")
    print(dot(m1,m3) + dot(m2,m3))
    print()
    print("(m1+m2).m3 - (m1.m3 + m2.m3) is equal to: \n")
    print(dot((m1+m2),m3) - (dot(m1,m3) + dot(m2,m3)))
    print()
    print("---------------------------------------------------------------")

    print("This is part 5.")
    print()
    print("(m1(m2(v)) is equal to: \n")
    print(dot(m1, dot(m2,v)))
    print()
    print("(m1.m2)(v) is equal to: \n")
    print(dot(dot(m1,m2),v))
    print()
    print("(m1(m2(v)) - (m1.m2)(v) is equal to: \n")
    print(dot(m1, dot(m2,v)) - dot(dot(m1,m2),v))
    print()
    print("---------------------------------------------------------------")

    print("This is part 6.")
    print()
    print("det(m1).det(m2) is equal to: \n")
    print(det(m1)*det(m2))
    print()
    print("det(m1.m2) is equal to: \n")
    print(det(dot(m1,m2)))
    print()
    print("det(m1).det(m2) - det(m1.m2) is equal to: \n")
    print(det(m1)*det(m2) - det(dot(m1,m2)))
    print()
    print("---------------------------------------------------------------")

    print("This is part 7.")
    print()
    print("m1.inv(m1) is equal to: \n")
    print(dot(m1, inv(m1)))
    print()
    print("inv(m1).m1 is equal to: \n")
    print(dot(inv(m1), m1))
    print()
    print("m1.inv(m1) - inv(m1).m1 is equal to: \n")
    print(dot(m1, inv(m1)) - dot(inv(m1), m1))
    print()
    print("---------------------------------------------------------------")
